### ISSUE TITLE
[Question] MoreCompany cosmetics

### ISSUE THREAD

**Issue by JohnMetroid** [Test-Account666/LethalCompany-TestAccountVariety#4]
Hey there,

I've been messing around with TestAccountVariety today and it has some really cool stuff in it.  It looks like there's options to disable pretty much everything except for the MoreCompany cosmetics.  Is there a way to do this I'm missing?

Cheers

**Comment by Test-Account666** [comment]
The cosmetics are loaded by MoreCompany.
You will have to disable them there

**Comment by JohnMetroid** [comment]
ah, perfect

thanks for the info!

![image](https://github.com/user-attachments/assets/0de59b30-0431-48e6-ae78-c8477dfb0ab5)
